import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseCheckout, quoteOrder, rial, normalizeDigits } from '../src/domain/commerce.ts';
const id = '11111111-1111-4111-8111-111111111111';
const now = Date.parse('2026-09-07T12:00:00Z');
const body = () => ({ idempotencyKey: id, items: [{variantId:id,quantity:2}], address:{recipientName:'کاربر آزمایشی',phone:'۰۹۱۲۱۲۳۴۵۶۷',province:'تهران',city:'تهران',addressLine:'نشانی ساختگی صرفاً برای آزمون',postalCode:'۱۲۳۴۵۶۷۸۹۰'} });
const catalog = () => [{id,published:true,active:true,sku:'TEST',name:'Test',quantityOnHand:5,quantityReserved:1,prices:[{amount:'10000000',currency:'IRR',active:true,startsAt:null,endsAt:null}]}];
const rejects = (fn, code) => assert.throws(fn, e => e.code === code);
test('normalizes Persian and Arabic digits', () => assert.equal(normalizeDigits('۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩'),'01234567890123456789'));
test('accepts and normalizes valid input', () => {const x=parseCheckout(body());assert.equal(x.address.phone,'09121234567');assert.equal(x.address.postalCode,'1234567890');});
for (const field of ['userId','total','role','discount','status']) test(`rejects client-controlled ${field}`,()=>rejects(()=>parseCheckout({...body(),[field]:'x'}),'UNEXPECTED_FIELD'));
test('rejects client line price',()=>{const b=body();b.items[0].price=1;rejects(()=>parseCheckout(b),'UNEXPECTED_FIELD')});
for(const quantity of [0,-1,11,1.5,'2',NaN,Infinity]) test(`rejects quantity ${quantity}`,()=>{const b=body();b.items[0].quantity=quantity;rejects(()=>parseCheckout(b),'INVALID_QUANTITY')});
test('rejects empty cart',()=>rejects(()=>parseCheckout({...body(),items:[]}),'INVALID_ITEMS'));
test('rejects duplicate variants',()=>{const b=body();b.items.push({...b.items[0]});rejects(()=>parseCheckout(b),'DUPLICATE_VARIANT')});
test('rejects unknown address fields',()=>{const b=body();b.address.role='admin';rejects(()=>parseCheckout(b),'UNEXPECTED_FIELD')});
test('rejects invalid phone',()=>{const b=body();b.address.phone='02112345678';rejects(()=>parseCheckout(b),'INVALID_PHONE')});
test('accepts international Iranian phone',()=>{const b=body();b.address.phone='+989121234567';assert.equal(parseCheckout(b).address.phone,'09121234567')});
test('rejects repeated postal code',()=>{const b=body();b.address.postalCode='1111111111';rejects(()=>parseCheckout(b),'INVALID_POSTAL_CODE')});
test('rejects invalid idempotency key',()=>rejects(()=>parseCheckout({...body(),idempotencyKey:'x'}),'INVALID_IDEMPOTENCY_KEY'));
test('uses server rial price without rounding',()=>{const q=quoteOrder(parseCheckout(body()),catalog(),now,500000);assert.equal(q.totalRial,20500000);assert.equal(q.currency,'IRR')});
test('accounts for reserved stock',()=>{const c=catalog();c[0].quantityReserved=4;rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'INSUFFICIENT_STOCK')});
test('refuses unpublished variants',()=>{const c=catalog();c[0].published=false;rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'UNAVAILABLE_VARIANT')});
test('refuses expired price at exact end boundary',()=>{const c=catalog();c[0].prices[0].endsAt=new Date(now).toISOString();rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'PRICE_UNAVAILABLE')});
test('accepts price at exact start boundary',()=>{const c=catalog();c[0].prices[0].startsAt=new Date(now).toISOString();assert.equal(quoteOrder(parseCheckout(body()),c,now,0).totalRial,20000000)});
test('refuses overlapping active prices',()=>{const c=catalog();c[0].prices.push({...c[0].prices[0]});rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'AMBIGUOUS_PRICE')});
test('refuses malformed price windows',()=>{const c=catalog();c[0].prices[0].endsAt='bad';rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'INVALID_PRICE_WINDOW')});
test('refuses implicit currency conversion',()=>{const c=catalog();c[0].prices[0].currency='IRT';rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'UNSUPPORTED_CURRENCY')});
test('detects multiplication overflow',()=>{const c=catalog();c[0].prices[0].amount=Number.MAX_SAFE_INTEGER;rejects(()=>quoteOrder(parseCheckout(body()),c,now,0),'INVALID_AMOUNT')});
for (const amount of [-1,1.1,'1e3',' 100','0x10',Infinity,null]) test(`rejects malformed money ${amount}`,()=>rejects(()=>rial(amount),'INVALID_AMOUNT'));
